# Generated by Django 4.0.4 on 2022-05-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userRole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='U_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='U_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='U_RolesFearutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userRole.u_features')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userRole.u_roles')),
            ],
        ),
        migrations.AddField(
            model_name='u_features',
            name='features',
            field=models.ManyToManyField(through='userRole.U_RolesFearutes', to='userRole.u_roles'),
        ),
    ]
